apiVersion: constraints.gatekeeper.sh/v1beta1
kind: NoRootContainers
metadata:
  name: no-root
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    namespaces:
      - "audit-zone"
  parameters:
    message: "Containers must run as non-root users for security compliance"