apiVersion: v1
kind: Pod
metadata:
  name: pod-no-hostpath
  namespace: audit-zone
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: nginx
      image: nginx:alpine
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        readOnlyRootFilesystem: true
      volumeMounts:
        - name: tmp-volume
          mountPath: /tmp
          readOnly: false
  volumes:
    - name: tmp-volume
      emptyDir: {}