apiVersion: audit.k8s.io/v1
kind: Policy
rules:

  - level: None
    resources:
      - group: ""
        resources: ["events"]
  
  - level: None
    users: ["system:kube-proxy"]
    verbs: ["watch"]
    resources:
      - group: ""
        resources: ["endpoints", "services"]
  
  - level: None
    userGroups: ["system:authenticated"]
    nonResourceURLs:
      - "/api*"
      - "/version"
      - "/healthz"
      - "/livez"
      - "/readyz"
      - "/metrics"
  

  - level: RequestResponse
    verbs: ["create", "delete", "update", "patch"]
    resources:
      - group: ""
        resources: ["pods", "secrets", "configmaps"]
  
  - level: RequestResponse
    verbs: ["get", "list"]
    resources:
      - group: ""
        resources: ["serviceaccounts", "roles", "rolebindings"]
  
  - level: Metadata
    omitStages:
      - "RequestReceived"